---
- hosts: all
  become: yes
  gather_facts: no

  tasks:

  - name: install ntp
    apt: name=ntp state=present update_cache=yes

  - name: copy ntp.conf
    copy: src=/home/vagrant/conf-files/ntp.conf dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: start ntp
    service: name=ntp state=started

  handlers:

  - name: restart ntp
    service: name=ntp state=restarted
